### ISSUE TITLE
Compatibility check to js-controller 4.0

### ISSUE THREAD

**Issue by ioBrokerChecker** [nbuenger/ioBroker.govee#11]
Dear Adapter developer,

with js-controller 4.0 object definitions are now also checked that min/max in only provided for number/mixed objects and that the type of the default value matches to the object type.

If something is not correct this is logged as 'warning' or 'info' log.

Please also make sure to update to the lastest @iobroker/testing dependency 2.5.4 or to accept the PR from Apollon77 for legacy testing!

Please spent some time to verify your adapter by ideally starting with a fresh instance and do some actions and verify the log. If you see a warn or info log there from these checks please adjust the adapter and fix the relevant cases.

For questions please refer to ioBroker/ioBroker.js-controller#1749

Please close the issue after you checked it.

Thank you very much for your support to get the best experience for the growing numbers of ioBroker users!

**Comment by JB1985** [comment]
Wäre klasse wenn da ein fix kommen könnte.

`
govee.0 | 2023-07-05 13:52:13.200 | error | Error: undefined is not a valid state value at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/maybeCallback.js:35:17) at Govee._setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5388:49) at Govee.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5349:21) at /opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2043:16 at new Promise (<anonymous>) at Govee.setStateAsync (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2042:16) at /opt/iobroker/node_modules/iobroker.govee/main.js:834:16 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
-- | -- | -- | --
govee.0 | 2023-07-05 13:52:13.200 | error | unhandled promise rejection: undefined is not a valid state value
govee.0 | 2023-07-05 13:52:13.200 | error | undefined is not a valid state value
govee.0 | 2023-07-05 13:52:13.199 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
govee.0 | 2023-07-05 13:52:13.198 | error | undefined is not a valid state value
`
