### ISSUE TITLE
Request failed with status code 429

### ISSUE THREAD

**Issue by denjo1982** [nbuenger/ioBroker.govee#26]
Hallo ich habe immer folgende Fehlermeldung:

`govee.0 | 2024-05-27 15:03:10.061 | error | AxiosError: Request failed with status code 429`

**Comment by denjo1982** [comment]
`govee.0 | 2024-05-27 15:20:00.882 | error | undefined is not a valid state value
-- | -- | -- | --
govee.0 | 2024-05-27 15:20:00.881 | error | Error: undefined is not a valid state value at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/maybeCallback.js:35:17) at Govee._setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5446:49) at Govee.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5406:21) at /opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2022:16 at new Promise (<anonymous>) at Govee.setStateAsync (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2021:16) at Govee.onStateChange (/opt/iobroker/node_modules/iobroker.govee/main.js:293:14) at runNextTicks (node:internal/process/task_queues:60:5) at process.processImmediate (node:internal/timers:449:9)
govee.0 | 2024-05-27 15:20:00.881 | error | unhandled promise rejection: undefined is not a valid state value
govee.0 | 2024-05-27 15:20:00.880 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().`

**Comment by EisTee94** [comment]
Moin, tatsächlich taucht der error bei mir auch immer mal wieder aus. Hab leider noch keinen WorkAround gefunden.
Der Adapter scheint nicht mehr bearbeitet zu werden. 
Ich spüre keine einschränkung, auser ne volle Log ;)
