### ISSUE TITLE
Issue while install of Adapter 

### ISSUE THREAD

**Issue by thomasklein1975** [nbuenger/ioBroker.govee#9]
Hi,

I have got problem to install adapter by using github link.

Node: 14.17
NPM: 6.14.13
JS-Controller: 3.3.18

This is shown while install:

`$ ./iobroker url "https://github.com/nbuenger/ioBroker.govee" --debug
install nbuenger/ioBroker.govee#0d983c49135b87ac2f88f9d832a6d632c4889606
NPM version: 6.14.13npm install nbuenger/ioBroker.govee#0d983c49135b87ac2f88f9d832a6d632c4889606 --prefix "/opt/iobroker" (System call)

> authenticate-pam@1.0.2 install /opt/iobroker/node_modules/authenticate-pam> node-gyp rebuild
make: Entering directory '/opt/iobroker/node_modules/authenticate-pam/build'
  CXX(target) Release/obj.target/authenticate_pam/authenticate_pam.o
../authenticate_pam.cc: In function ‘void after_doing_auth(uv_work_t*, int)’:
../authenticate_pam.cc:107:87: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), Nan::New(m->callback), 1, args);                                                                                       ^In file included from ../authenticate_pam.cc:23:../../nan/nan.h:1026:46: note: declared here   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(                                              ^~~~~~~~~~~~../authenticate_pam.cc:107:87: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), Nan::New(m->callback), 1, args);                                                                                       ^In file included from ../authenticate_pam.cc:23:../../nan/nan.h:1026:46: note: declared here   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(                                              ^~~~~~~~~~~~
../authenticate_pam.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Authenticate(Nan::NAN_METHOD_ARGS_TYPE)’:../authenticate_pam.cc:147:83: error: no matching function for call to ‘v8::Array::Get(v8::Local<v8::String>)’   Local<Value> res = options->Get(Nan::New<String>("serviceName").ToLocalChecked());                                                                                   ^In file included from /home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:67,                 from ../../nan/nan.h:56,                 from ../authenticate_pam.cc:23:/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3717:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)’   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,                                           ^~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3717:43: note:   candidate expects 2 arguments, 1 provided/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3720:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)’   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,                                           ^~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3720:43: note:   candidate expects 2 arguments, 1 provided../authenticate_pam.cc:150:69: error: no matching function for call to ‘v8::String::WriteUtf8(char [128], unsigned int)’    serviceName->WriteUtf8(m->serviceName, sizeof(m->serviceName) - 1);                                                                     ^In file included from /home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:67,                 from ../../nan/nan.h:56,                 from ../authenticate_pam.cc:23:/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3037:7: note: candidate: ‘int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const’   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,       ^~~~~~~~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3037:7: note:   no known conversion for argument 1 from ‘char [128]’ to ‘v8::Isolate*’../authenticate_pam.cc:152:69: error: no matching function for call to ‘v8::Array::Get(v8::Local<v8::String>)’   res = options->Get(Nan::New<String>("remoteHost").ToLocalChecked());                                                                     ^In file included from /home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:67,                 from ../../nan/nan.h:56,                 from ../authenticate_pam.cc:23:/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3717:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)’   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,                                           ^~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3717:43: note:   candidate expects 2 arguments, 1 provided/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3720:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)’   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,                                           ^~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3720:43: note:   candidate expects 2 arguments, 1 provided../authenticate_pam.cc:155:66: error: no matching function for call to ‘v8::String::WriteUtf8(char [128], unsigned int)’    remoteHost->WriteUtf8(m->remoteHost, sizeof(m->remoteHost) - 1);                                                                  ^In file included from /home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:67,                 from ../../nan/nan.h:56,                 from ../authenticate_pam.cc:23:/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3037:7: note: candidate: ‘int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const’   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,       ^~~~~~~~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3037:7: note:   no known conversion for argument 1 from ‘char [128]’ to ‘v8::Isolate*’../authenticate_pam.cc:160:58: error: no matching function for call to ‘v8::String::WriteUtf8(char [128], unsigned int)’  username->WriteUtf8(m->username, sizeof(m->username) - 1);                                                          ^In file included from /home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:67,                 from ../../nan/nan.h:56,                 from ../authenticate_pam.cc:23:/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3037:7: note: candidate: ‘int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const’   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,       ^~~~~~~~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3037:7: note:   no known conversion for argument 1 from ‘char [128]’ to ‘v8::Isolate*’../authenticate_pam.cc:161:58: error: no matching function for call to ‘v8::String::WriteUtf8(char [128], unsigned int)’  password->WriteUtf8(m->password, sizeof(m->password) - 1);                                                          ^In file included from /home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:67,                 from ../../nan/nan.h:56,                 from ../authenticate_pam.cc:23:/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3037:7: note: candidate: ‘int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const’   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,       ^~~~~~~~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3037:7: note:   no known conversion for argument 1 from ‘char [128]’ to ‘v8::Isolate*’../authenticate_pam.cc: At global scope:../authenticate_pam.cc:170:11: error: variable or field ‘init’ declared void void init(Handle<Object> exports) {           ^~~~~~../authenticate_pam.cc:170:11: error: ‘Handle’ was not declared in this scope../authenticate_pam.cc:170:11: note: suggested alternative: ‘rand_r’ void init(Handle<Object> exports) {           ^~~~~~           rand_r../authenticate_pam.cc:170:24: error: expected primary-expression before ‘>’ token void init(Handle<Object> exports) {                        ^../authenticate_pam.cc:170:26: error: ‘exports’ was not declared in this scope void init(Handle<Object> exports) {                          ^~~~~~~
In file included from ../../nan/nan.h:56,                 from ../authenticate_pam.cc:23:../authenticate_pam.cc:175:31: error: ‘init’ was not declared in this scope NODE_MODULE(authenticate_pam, init);                               ^~~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:758:36: note: in definition of macro ‘NODE_MODULE_X’       (node::addon_register_func) (regfunc),                          \                                    ^~~~~~~../authenticate_pam.cc:175:1: note: in expansion of macro ‘NODE_MODULE’ NODE_MODULE(authenticate_pam, init); ^~~~~~~~~~~../authenticate_pam.cc:175:31: note: suggested alternative: ‘int’ NODE_MODULE(authenticate_pam, init);                               ^~~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:758:36: note: in definition of macro ‘NODE_MODULE_X’       (node::addon_register_func) (regfunc),                          \                                    ^~~~~~~../authenticate_pam.cc:175:1: note: in expansion of macro ‘NODE_MODULE’ NODE_MODULE(authenticate_pam, init); ^~~~~~~~~~~
make: *** [authenticate_pam.target.mk:109: Release/obj.target/authenticate_pam/authenticate_pam.o] Error 1
make: Leaving directory '/opt/iobroker/node_modules/authenticate-pam/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)gyp ERR! stack     at ChildProcess.emit (events.js:376:20)gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)gyp ERR! System Linux 5.10.17-v7l+gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"gyp ERR! cwd /opt/iobroker/node_modules/authenticate-pamgyp ERR! node -v v14.17.0gyp ERR! node-gyp -v v5.1.0gyp ERR! not ok 
> @serialport/bindings@2.0.8 install /opt/iobroker/node_modules/iobroker.mysensors/node_modules/@serialport/bindings> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
prebuild-install WARN install No prebuilt binaries found (target=14.17.0 runtime=node arch=arm libc= platform=linux)
make: Entering directory '/opt/iobroker/node_modules/iobroker.mysensors/node_modules/@serialport/bindings/build'
  CXX(target) Release/obj.target/bindings/src/serialport.o
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Open(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:78:69: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]   uv_queue_work(uv_default_loop(), req, EIO_Open, (uv_after_work_cb)EIO_AfterOpen);                                                                     ^~~~~~~~~~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Update(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:135:71: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   uv_queue_work(uv_default_loop(), req, EIO_Update, (uv_after_work_cb)EIO_AfterUpdate);                                                                       ^~~~~~~~~~~~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Close(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:175:70: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]   uv_queue_work(uv_default_loop(), req, EIO_Close, (uv_after_work_cb)EIO_AfterClose);                                                                      ^~~~~~~~~~~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Flush(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:215:70: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]   uv_queue_work(uv_default_loop(), req, EIO_Flush, (uv_after_work_cb)EIO_AfterFlush);                                                                      ^~~~~~~~~~~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Set(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/serialport.cpp:270:68: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]   uv_queue_work(uv_default_loop(), req, EIO_Set, (uv_after_work_cb)EIO_AfterSet);                                                                    ^~~~~~~~~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Get(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:314:68: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   uv_queue_work(uv_default_loop(), req, EIO_Get, (uv_after_work_cb)EIO_AfterGet);                                                                    ^~~~~~~~~~~~
../src/serialport.cpp: In function ‘void EIO_AfterGet(uv_work_t*)’:../src/serialport.cpp:329:96: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Boolean>::return_t)’     results->Set(Nan::New<v8::String>("cts").ToLocalChecked(), Nan::New<v8::Boolean>(data->cts));                                                                                                ^In file included from /home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:67,                 from ../../../../../nan/nan.h:56,                 from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,                                     ^~~
/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,                                     ^~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided../src/serialport.cpp:330:96: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Boolean>::return_t)’     results->Set(Nan::New<v8::String>("dsr").ToLocalChecked(), Nan::New<v8::Boolean>(data->dsr));                                                                                                ^In file included from /home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:67,                 from ../../../../../nan/nan.h:56,                 from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,                                     ^~~
/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,                                     ^~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided../src/serialport.cpp:331:96: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Boolean>::return_t)’     results->Set(Nan::New<v8::String>("dcd").ToLocalChecked(), Nan::New<v8::Boolean>(data->dcd));                                                                                                ^In file included from /home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:67,                 from ../../../../../nan/nan.h:56,                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,                                     ^~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,                                     ^~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE GetBaudRate(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:363:76: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]   uv_queue_work(uv_default_loop(), req, EIO_GetBaudRate, (uv_after_work_cb)EIO_AfterGetBaudRate);                                                                            ^~~~~~~~~~~~~~~~~~~~
../src/serialport.cpp: In function ‘void EIO_AfterGetBaudRate(uv_work_t*)’:../src/serialport.cpp:378:106: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::IntegerFactory<v8::Integer>::return_t)’     results->Set(Nan::New<v8::String>("baudRate").ToLocalChecked(), Nan::New<v8::Integer>(data->baudRate));                                                                                                          ^In file included from /home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:67,                 from ../../../../../nan/nan.h:56,                 from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,                                     ^~~
/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,                                     ^~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Drain(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:409:70: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]   uv_queue_work(uv_default_loop(), req, EIO_Drain, (uv_after_work_cb)EIO_AfterDrain);                                                                      ^~~~~~~~~~~~~~
../src/serialport.cpp: At global scope:../src/serialport.cpp:430:28: warning: unnecessary parentheses in declaration of ‘ToParityEnum’ [-Wparentheses] SerialPortParity NAN_INLINE(ToParityEnum(const v8::Local<v8::String>& v8str)) {                            ^../src/serialport.cpp:449:30: warning: unnecessary parentheses in declaration of ‘ToStopBitEnum’ [-Wparentheses] SerialPortStopBits NAN_INLINE(ToStopBitEnum(double stopBits)) {                              ^
In file included from ../../../../../nan/nan.h:56,                 from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:/home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:758:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]       (node::addon_register_func) (regfunc),                          \                                           ^/home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:792:3: note: in expansion of macro ‘NODE_MODULE_X’   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)   ^~~~~~~~~~~~~../src/serialport.cpp:483:1: note: in expansion of macro ‘NODE_MODULE’ NODE_MODULE(serialport, init); ^~~~~~~~~~~
make: *** [bindings.target.mk:112: Release/obj.target/bindings/src/serialport.o] Error 1
make: Leaving directory '/opt/iobroker/node_modules/iobroker.mysensors/node_modules/@serialport/bindings/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)gyp ERR! stack     at ChildProcess.emit (events.js:376:20)gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)gyp ERR! System Linux 5.10.17-v7l+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"gyp ERR! cwd /opt/iobroker/node_modules/iobroker.mysensors/node_modules/@serialport/bindingsgyp ERR! node -v v14.17.0gyp ERR! node-gyp -v v5.1.0gyp ERR! not ok 
npm WARN jscs-loader@0.3.0 requires a peer of jscs@^3.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.7 (node_modules/osx-temperature-sensor):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-temperature-sensor@1.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/zigbee-herdsman-converters/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/fsevents):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/zigbee-herdsman/node_modules/fsevents):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: authenticate-pam@1.0.2 (node_modules/authenticate-pam):npm WARN optional SKIPPING OPTIONAL DEPENDENCY: authenticate-pam@1.0.2 install: `node-gyp rebuild`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @serialport/bindings@2.0.8 (node_modules/iobroker.mysensors/node_modules/@serialport/bindings):npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @serialport/bindings@2.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
+ iobroker.govee@0.0.5updated 1 package in 188.168s
146 packages are looking for funding  run `npm fund` for details
upload [5] govee.admin /opt/iobroker/node_modules/iobroker.govee/admin/words.js words.js application/javascript
upload [4] govee.admin /opt/iobroker/node_modules/iobroker.govee/admin/style.css style.css text/css
upload [3] govee.admin /opt/iobroker/node_modules/iobroker.govee/admin/index_m.html index_m.html text/html
upload [2] govee.admin /opt/iobroker/node_modules/iobroker.govee/admin/govee.png govee.png image/png
upload [1] govee.admin /opt/iobroker/node_modules/iobroker.govee/admin/govee-old.png govee-old.png image/png
upload [0] govee.admin /opt/iobroker/node_modules/iobroker.govee/admin/admin.d.ts admin.d.ts video/mp2t
process exited with code 0`

There is no adapter in instance overview to be seen. Maybe somehon can help be.

**Comment by Beast-Panik** [comment]
I have the same problem. After installing the Apadter it appears briefly and then disappears again.

**Comment by Grothesk242** [comment]
If adapter 'terminal' is installed, please kick it out.
